spring:
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 2525
    username: 'd4d4c1c49e5101'
    password: 'ed0ab70b52f5eb'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  # http://localhost:8080/h2-console
  # JDBC URL:  jdbc:h2:mem:testdb
  # haslo: password


  #mail:
    #host: 'sandbox.smtp.mailtrap.io'
    #port: 2525
    #username: 'd4d4c1c49e5101'
    #password: 'ed0ab70b52f5eb'
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true
